[package]
name = "sms_freemobile_api"
version = "0.2.0"
authors = ["Christian FOUCHER <christian.foucher@medianesysteme.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
toml = "*"
serde = "*"
serde_derive = "*"
